### ISSUE TITLE
🐛 [BUG] 安装此模块后 Roblox 无法全屏

### ISSUE THREAD

**Issue by mcxiaolan** [sothx/mipad-magic-window#10]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

Roblox (com.roblox.client) 在启用这个模块的时候就无法全屏了，右下角的重启按钮点了也没用

### 冷门应用安装包

在 Google Play 可下载

### 复现步骤

```bash
启动软件就这样
```

### 问题截图

![Screenshot_2024-06-09-17-27-00-072_com roblox client](https://github.com/sothx/mipad-magic-window/assets/66471947/754cda36-e75b-444f-8066-d36fb9f796d3)
![Screenshot_2024-06-09-17-29-54-903_io github huskydg magisk](https://github.com/sothx/mipad-magic-window/assets/66471947/36efd31f-61e5-4e4f-9d81-8cab2a73405d)

### 已安装模块的设备信息

设备型号：Xiaomi Pad 6 Pro
系统版本：MIUI Pad 14.0.9

**Comment by sothx** [comment]
版本号1.19.31已经修复此问题。
原因：新发布平板的配置文件中，小米追加了该应用的信箱模式，导致无法正常全屏。
