### ISSUE TITLE
💡 [适配需求] <能否适配一下cctalk>

### ISSUE THREAD

**Issue by zz447845146** [sothx/mipad-magic-window#11]
### 适配需求内容

如题

### 额外描述

```bash
我已为应用名称（包名称）做了适配，代码如下，望采纳 '...'
我希望应用名称（包名称）的适配效果是这样的 '....'
....
```

**Comment by sothx** [comment]
这个应用无法适配，全屏化后会导致应用卡首屏。

**Comment by zz447845146** [comment]
改成平行世界也不行吗
现在这样居中挺不方便的

**Comment by sothx** [comment]
> 改成平行世界也不行吗 现在这样居中挺不方便的

最新版本已经调整了居中下显示的大小了，可以试试。

CCTalk配置了不允许平板厂家反向适配平行视界，因此没办法改成平行视界。
