### ISSUE TITLE
问题：momo会显示找到被 Magisk 模块修改的文件

### ISSUE THREAD

**Issue by qianzhou123** [sothx/mipad-magic-window#13]
在安装模块后momo会显示找到被 Magisk 模块修改的文件。
![Screenshot_2024-07-11-22-53-14-798_io github vvb2060 mahoshojo](https://github.com/sothx/mipad-magic-window/assets/111413182/f6c5b672-ae41-4199-bad7-2c0bf822c065)
在卸载后又不会显示
型号：小米平板6
最新版本仍有该问题

**Comment by sothx** [comment]
这不属于模块缺陷，因为小米平板6缺失"应用布局优化"相关资源，因此模块进行了补充，而且这个也不会对系统又什么影响。
你可以改用安卓13/通用版模块，就不会报此修改，同时也无法正常使用"应用布局优化"相关功能。

**Comment by sothx** [comment]
这不属于模块缺陷，因为小米平板6缺失"应用布局优化"相关资源，因此模块进行了补充，而且这个也不会对系统又什么影响。
你可以改用安卓13/通用版模块，就不会报此修改，同时也无法正常使用"应用布局优化"相关功能。
