### ISSUE TITLE
🐛 [BUG] 穿越火线适配问题

### ISSUE THREAD

**Issue by mcxiaolan** [sothx/mipad-magic-window#16]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

穿越火线 (com.tencent.tmgp.cf)  
搜了一下 repo, 确实有关于 cf 的东东，但我不懂hhh

### 复现步骤

```bash
进入游戏
```

### 问题截图

![Screenshot_2024-07-27-00-43-28-412_com tencent tmgp cf](https://github.com/user-attachments/assets/30337501-5fe5-427b-99bc-1af9659d84bf)

### 已安装模块的设备信息

设备型号：Xiaomi Pad 6 Pro
系统版本：hyperOS 1.0.5.0.UMYCNXM

**Comment by sothx** [comment]
该功能属于模块补全的"游戏显示布局"，这里是使用文档，可以开启管理面板：
https://hyper-magic-window.sothx.com/game-mode.html

如果不需要该功能，也可以卸载模块，安装的时候针对"游戏显示布局"的选项选择否。

**Comment by mcxiaolan** [comment]
> 该功能属于模块补全的"游戏显示布局"，这里是使用文档，可以开启管理面板： https://hyper-magic-window.sothx.com/game-mode.html
> 
> 如果不需要该功能，也可以卸载模块，安装的时候针对"游戏显示布局"的选项选择否。

试了一下，启动不了这个 activity  
Hyper Ceiler 能开折叠屏专区，但是点游戏显示布局和启动 activity 一样  
我卸载模块重装试试

**Comment by sothx** [comment]
> > 该功能属于模块补全的"游戏显示布局"，这里是使用文档，可以开启管理面板： https://hyper-magic-window.sothx.com/game-mode.html
> > 如果不需要该功能，也可以卸载模块，安装的时候针对"游戏显示布局"的选项选择否。
> 
> 试了一下，启动不了这个 activity, 直接出来了 Hyper Ceiler 能开折叠屏专区，但是点游戏显示布局和启动 activity 一样 我卸载模块重装试试

看看重装能否解决呢？qwq

**Comment by mcxiaolan** [comment]
> > > 该功能属于模块补全的"游戏显示布局"，这里是使用文档，可以开启管理面板： https://hyper-magic-window.sothx.com/game-mode.html
> > > 如果不需要该功能，也可以卸载模块，安装的时候针对"游戏显示布局"的选项选择否。
> > 
> > 
> > 试了一下，启动不了这个 activity, 直接出来了 Hyper Ceiler 能开折叠屏专区，但是点游戏显示布局和启动 activity 一样 我卸载模块重装试试
> 
> 看看重装能否解决呢？qwq

应该算好了，但是启动的时候遮罩和卸载时不一样，这个应该影响不大？（（
![Screenshot_2024-07-27-01-29-27-377_com tencent tmgp cf](https://github.com/user-attachments/assets/cf8dfe8a-e1a7-4577-a464-c230ef01b391)

**Comment by sothx** [comment]
这个问题已经在1.21.15模块版本修复，可以尝试更新。
由于OPPO的工程师在OnePlus Pad上给CF手游配置了错误的信箱模式，导致同步过来后也有这样的问题。
