### ISSUE TITLE
🐛 [BUG] 必剪时间轴错位

### ISSUE THREAD

**Issue by mcxiaolan** [sothx/mipad-magic-window#18]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

截图，预览位置和下方时间轴不同  
希望能修吧，这剪辑软件还是很好用的，巧影原版横屏还可以，但是渲染视频总是报错

### 复现步骤

```bash
编辑视频
```

### 问题截图

![Screenshot_2024-08-23-18-05-49-899_com bilibili studio](https://github.com/user-attachments/assets/6ee4ab4e-73b1-4389-a937-166df07fc3e0)
![Screenshot_2024-08-23-18-05-53-198_com bilibili studio](https://github.com/user-attachments/assets/c00be363-8809-4fe0-b8a0-2ee1e03f1b90)

### 已安装模块的设备信息

设备型号：Xiaomi Pad 6 Pro
系统版本：OS 1.0.7.0.UMYCNXM

**Comment by sothx** [comment]
1.23.53版本已经修复此问题

**Comment by sothx** [comment]
请确认问题是否已解决，如果没问题，三天后会关闭该issues

**Comment by mcxiaolan** [comment]
> 请确认问题是否已解决，如果没问题，三天后会关闭该issues

我这里还是没有解决，这是不给 hyperCeiler root 权限，重启后的截图  
我也不知道是不是我开的什么模块的问题
![Screenshot_2024-08-28-21-58-57-929_me bmax apatch](https://github.com/user-attachments/assets/299a4552-f5c6-40dd-a834-7d6bebb0cdd8)

**Comment by mcxiaolan** [comment]
刚刚试了一下关闭lsp模块和ceiler的root权限，一样

**Comment by sothx** [comment]
> 刚刚试了一下关闭lsp模块和ceiler的root权限，一样 忘记截图了，现在附上一张截图 ![Screenshot_2024-08-28-22-10-56-346_com bilibili studio](https://private-user-images.githubusercontent.com/66471947/362319215-1ce8713a-0b7c-44fa-a6fd-00ccfe356127.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NjMyMjEsIm5iZiI6MTcyNDk2MjkyMSwicGF0aCI6Ii82NjQ3MTk0Ny8zNjIzMTkyMTUtMWNlODcxM2EtMGI3Yy00NGZhLWE2ZmQtMDBjY2ZlMzU2MTI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIwMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMDAyZDBhN2NmMmUyYzI4YTlhNDE1OTlkYzY5ZGMxY2UxYzY0NzZhOTFhMDU2NWY3MmMxNzg5NTIwZmEzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCqO9t2FjgvnJXW2QzcCwNELDsQx_gfX9PlZFLhWe9I)

尝试一下最新版的1.23.59？目前怀疑可能是应用布局优化导致的额外问题，新版本模块已经移除必剪的应用布局优化适配规则了。

**Comment by mcxiaolan** [comment]
> > 刚刚试了一下关闭lsp模块和ceiler的root权限，一样 忘记截图了，现在附上一张截图 ![Screenshot_2024-08-28-22-10-56-346_com bilibili studio](https://private-user-images.githubusercontent.com/66471947/362319215-1ce8713a-0b7c-44fa-a6fd-00ccfe356127.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NjMyMjEsIm5iZiI6MTcyNDk2MjkyMSwicGF0aCI6Ii82NjQ3MTk0Ny8zNjIzMTkyMTUtMWNlODcxM2EtMGI3Yy00NGZhLWE2ZmQtMDBjY2ZlMzU2MTI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDIwMjIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMDAyZDBhN2NmMmUyYzI4YTlhNDE1OTlkYzY5ZGMxY2UxYzY0NzZhOTFhMDU2NWY3MmMxNzg5NTIwZmEzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZCqO9t2FjgvnJXW2QzcCwNELDsQx_gfX9PlZFLhWe9I)
> 
> 尝试一下最新版的1.23.59？目前怀疑可能是应用布局优化导致的额外问题，新版本模块已经移除必剪的应用布局优化适配规则了。

好了🥳感谢作者大大！早点休息😊
