### ISSUE TITLE
🐛 [BUG] wakeup课程表 桌面小部件样式页面无法正常显示

### ISSUE THREAD

**Issue by OnismIS** [sothx/mipad-magic-window#19]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

WakeUp课程表（com.suda.yzune.wakeupschedule）点击桌面小部件右上角的样式调整按钮进入小部件样式页面无法正常显示（如图一），设置中关闭该应用的应用布局优化后可正常显示（如图二）
![Screenshot_2024-09-05-15-06-41-524_com suda yzune wakeupschedule](https://github.com/user-attachments/assets/e3eee82c-bcd4-4eb0-ab81-03e2aa19a312)
![1000024504](https://github.com/user-attachments/assets/b16cf9fa-1eac-4da1-b45c-89886fe976cb)

### 复现步骤

```bash
1. 进入 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 已安装模块的设备信息

设备型号：……
系统版本：……

**Comment by sothx** [comment]
您好，感谢反馈，该问题已在1.23.88修复，可以尝试是否已解决。

**Comment by OnismIS** [comment]
> 您好，感谢反馈，该问题已在1.23.88修复，可以尝试是否已解决。

最新版本测试已解决，感谢修复
