### ISSUE TITLE
🐛 [BUG] <哔哩哔哩横屏视频全屏后退不出来>

### ISSUE THREAD

**Issue by gangtieya233** [sothx/mipad-magic-window#2]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

哔哩哔哩 包名tv.danmaku.bili
横屏视频全屏后，返回不到评论区页面

### 复现步骤

```bash
1. 进入 横屏视频
2. 点击 全屏
3. 返回

....
出现问题
屏幕重新分成37，但是全屏视频还是全屏
```

### 问题截图

![image](https://github.com/sothx/mipad-magic-window/assets/111995151/cdd1a9c2-03ca-44d0-805b-04e4fc4f858b)
![image](https://github.com/sothx/mipad-magic-window/assets/111995151/4a7464f4-b048-4aec-8cbf-12df3783ff49)

### 已安装模块的设备信息

设备型号：小米平板6pro
系统版本：miui14.0.9

**Comment by sothx** [comment]
如果是
