### ISSUE TITLE
🐛 [BUG] <tiktok显示错误，横屏时强制裁剪视频>

### ISSUE THREAD

**Issue by 0fuling0** [sothx/mipad-magic-window#20]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

com.ss.android.ugc.trill或com.zhiliaoapp.musically，首次打开后显示正常，再次打开后所有视频强制裁剪成全屏。

### 冷门应用安装包

链接:https://caiyun.139.com/m/i?0o5CM0bdZ9PVE
提取码:KoDM
复制内容打开移动云盘PC客户端，操作更方便哦

### 复现步骤

```bash
首次打开后显示正常，再次打开后所有视频强制裁剪成全屏。
```

### 问题截图

![Screenshot_2024-09-15-21-56-29-493_com ss android ugc trill](https://github.com/user-attachments/assets/fa2c066d-83bd-46e7-86d0-3d93608faeea)
![Screenshot_2024-09-15-22-03-24-887_com zhiliaoapp musically](https://github.com/user-attachments/assets/f6a9454a-df22-43b8-ac88-22b9ca6fea2a)

### 已安装模块的设备信息

设备型号：……
系统版本：……

**Comment by sothx** [comment]
1.23.126已经修改了这两个应用的横屏配置，请测试是否正常

**Comment by 0fuling0** [comment]
已更新pad-1.23.126，问题依旧存在。安装后首次打开应用正常，再次打开则裁剪竖向视频。关闭模块后用小窗拉一个横屏，也能复现。猜测是tiktok本身的问题，但是首次打开可以正常显示，就很怪。

**Comment by sothx** [comment]
1.23.127,已经尝试统一国际版tiktok的规则为国内版，如果仍然无效，可以尝试[设置-平行窗口]，关闭这个应用的平行窗口开关，看看是否正常。

**Comment by 0fuling0** [comment]
反复开关，依旧异常。猜测是tiktok本身的问题，这个和国内版还是有点区别的。建议关闭问题。
