### ISSUE TITLE
神州e学通横屏闪退

### ISSUE THREAD

**Issue by wayner6** [sothx/mipad-magic-window#22]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

神州e学通(com.stjy.stjp.student)横屏进入会闪退，竖屏可正常使用，只要横屏就还是会闪退

### 冷门应用安装包

可直接在小米应用商店下载

### 复现步骤

```bash
1. 横屏状态下进入 '神州e学通'APP或者在软件内部旋转屏幕为横屏
2. 闪退
```

### 已安装模块的设备信息

设备型号：小米 Pad 6 Pro (liuqin)
系统版本：OS1.0.10.0.UMYCNXM
安卓版本：14

**Comment by sothx** [comment]
这个应用需要提供账号，之前在酷安提供的QQ找不到联系人

**Comment by sothx** [comment]
如果不能提供账号信息，该issues将关闭
