### ISSUE TITLE
[FR]KsuWebUI darkmode

### ISSUE THREAD

**Issue by nlsdt** [sothx/mipad-magic-window#23]
希望能增加webui深色模式，晚上刷完模块差点被晃瞎了。谢谢
PS：magisk也能KsuWebUI了，好耶 [KsuWebUI For Magisk](https://github.com/5ec1cff/KsuWebUIStandalone)

**Comment by sothx** [comment]
深色模式的适配处于计划中，等目前优先级高的功能先整完，会增加Web UI的深色模式

**Comment by sothx** [comment]
新版已增加深色模式
