### ISSUE TITLE
微信小程序不能全屏显示

### ISSUE THREAD

**Issue by 160725** [sothx/mipad-magic-window#25]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

微信小程序不能全屏显示
两边是白边

### 复现步骤

```bash
1. 进入 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 已安装模块的设备信息

设备型号：……
系统版本：……

**Comment by sothx** [comment]
微信是腾讯自己适配的，目前模块暂时无法反向干预应用自适配平行窗口的规则。
