### ISSUE TITLE
🐛 [BUG] MIUI14专版pipa机型卡第一屏

### ISSUE THREAD

**Issue by DTY77** [sothx/mipad-magic-window#26]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

卡开机第一屏。

版本：pad-miui-based-on-tiramisu-2.05.37.zip
设备：小米平板6 代号：pipa
固件版本：国行MIUI14.0.7

### 复现步骤

```bash
1. 进入 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 已安装模块的设备信息

设备型号：……
系统版本：……

**Comment by sothx** [comment]
通用版模块几乎不会动任何system的东西，仅替换系统文件，按道理不会卡第一屏，有具体的错误日志么？
或者提供QQ之类的联系方式

**Comment by DTY77** [comment]
不，他并非通用版。在说明文件里，他是如下描述：
小米平板6系列MIUI14专版(pad-miui-based-on-tiramisu-x.xx.xx.zip)
我使用的是该版本

**Comment by sothx** [comment]
> 不，他并非通用版。在说明文件里，他是如下描述： 小米平板6系列MIUI14专版(pad-miui-based-on-tiramisu-x.xx.xx.zip) 我使用的是该版本

好的，方便提供一下联系方式么，我重新修改一版给你测试，但是因为我没有小米平板6，可能需要帮我测测

**Comment by DTY77** [comment]
好的谢谢你。我提供我的邮箱
dty2628993464@gmail.com

**Comment by sothx** [comment]
[pad-miui-based-on-tiramisu-2.05.39.zip](https://github.com/user-attachments/files/18208336/pad-miui-based-on-tiramisu-2.05.39.zip)

请尝试该修复包是否已经解决了这个问题

**Comment by DTY77** [comment]
不好意思，现在才有时间进行测试，我会尽快把测试结果告诉您，
同时，再次感谢您对模块的维护。












2628993464
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月20日(周五) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sothx/mipad-magic-window] 🐛 [BUG] MIUI14专版pipa机型卡第一屏 (Issue #26)




 
pad-miui-based-on-tiramisu-2.05.39.zip
 
请尝试该修复包是否已经解决了这个问题

**Comment by DTY77** [comment]
不好意思，现在才有时间进行测试，我会尽快把测试结果告诉您，同时，再次感谢您对模块的维护。2024年12月20日 下午11:34，2628993464 ***@***.***>***@***.***原始邮件---发件人: ***@***.***>发送时间: 2024年12月20日(周五) 下午4:55收件人: ***@***.***>;抄送: ***@***.***>***@***.***>;主题: Re: [sothx/mipad-magic-window] 🐛 [BUG] MIUI14专版pipa机型卡第一屏 (Issue #26)
pad-miui-based-on-tiramisu-2.05.39.zip
请尝试该修复包是否已经解决了这个问题

**Comment by DTY77** [comment]
在最新的2.05.41版本已经不在卡米。
pad-miui-based-on-tiramisu-2.05.41.zip
小米平板6系列MIUI14专用版，谢谢

Sothx ***@***.***> 于 2024年12月20日周五 下午4:55写道：
