### ISSUE TITLE
💡 [适配需求] 增加软件dpi配置

### ISSUE THREAD

**Issue by Dome-World** [sothx/mipad-magic-window#4]
### 适配需求内容

考虑到一些软件在平行视界下字体大小发生变化，请问能有修改单个软件dpi的参数吗，想调一下b站的。

**Comment by sothx** [comment]
《完美横屏应用计划》不会考虑此需求，Android Embedded Activity依赖此判断决定是否显示平行视界，修改应用DPI可能导致平行视界不能正常显示。
可以自行搜索相关模块，并且可能需要修改对应应用的splitMinWidth，否则可能会丢失该应用的平行视界。
