### ISSUE TITLE
🐛 [BUG] <b站多次点开推荐视频后，再返回却直接回到了主页>

### ISSUE THREAD

**Issue by fengXL** [sothx/mipad-magic-window#9]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已阅读过模块首页的问题合集，确认不属于问题合集中提及的问题。
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

哔哩哔哩横屏使用时，点击推荐视频后想要返回前一页，结果直接返回了主页。竖屏使用时正常

### 复现步骤

```bash
1.随便点进一个视频a
2.随便点开视频a的推荐视频
3.返回
问题出现:此时应该返回的是视频a的页面，结果返回了b站主页
```

### 问题截图

![图片注释](图片链接)

### 已安装模块的设备信息

小米平板5pro
hyperos 1.0.2

**Comment by sothx** [comment]
手机端目前是相同的逻辑，推荐视频点进去是覆盖当前视频的逻辑，并不支持返回功能，因此也是回到首页而非上一个。

**Comment by Kingdomhui** [comment]
1. 没刷模块

https://github.com/user-attachments/assets/f2f65943-d558-4093-aa12-3d0534f44027

2.刷模块后

https://github.com/user-attachments/assets/a6b1f2bb-7a69-4031-ac12-a02268b5c9da

搜索后无法返回上一层

**Comment by sothx** [comment]
> 1. 没刷模块
> 
>  default.mp4 
> 2.刷模块后
> 
>  default.mp4 
> 搜索后无法返回上一层

您好，该问题已经在1.23.17版本修复，请验收。如有异常可以继续反馈。

**Comment by Kingdomhui** [comment]
> > 1. 没刷模块
> > 
> > default.mp4
> > 2.刷模块后
> > default.mp4
> > 搜索后无法返回上一层
> 
> 您好，该问题已经在1.23.17版本修复，请验收。如有异常可以继续反馈。

感谢大佬
